### ISSUE TITLE
allowed-packages is not working

### ISSUE THREAD

**Issue by francma** [MetaSyntactical/composer-plugin-license-check#353]
See lines at https://github.com/MetaSyntactical/composer-plugin-license-check/blob/09a6db6081608d61cdc5d4ecaa7d052b5983023b/src/Command/CheckLicensesCommand.php#L193C10-L195C10

The issue is that `$allowedPackages` is a list of packages in this format:

```
[0 => "package1", 1 => "package2"]
```

and the code looks for the keys of the array, not values:

```php
if (!$allowedToUse && array_key_exists($package->getPrettyName(), $allowedPackages)) {
    $isAllowed = true;
}
```

**Comment by dkreuer** [comment]
That’s correct. The documentation is missing a little bit. Allowed packages configuration is future-proof as it allows specifying package names and version constraints (same as `require` or `require-dev`) but the version constraints are currently not checked.
