### ISSUE TITLE
What is up with the nikic/php-parser >= 5.0.0 conflict? 

### ISSUE THREAD

**Issue by pelmered** [MetaSyntactical/composer-plugin-license-check#430]
I had to remove this package from my project because of this conflict. 
What is the conflict and is there a way around this? 

In my case it is https://github.com/pestphp/pest-plugin-mutate/ that needs `nikic/php-parser` of `^5.2.0` and I need that more than this package for daily development.

**Comment by dreeh** [comment]
Same for me. nikic/php-parser > 5.0.0 is needed for phpunit 11.

**Comment by dkreuer** [comment]
Thanks for bringing this to my attention.

**Comment by dreeh** [comment]
thank you for completing :-)

**Comment by pelmered** [comment]
Thank you @dkreuer! 

Reinstalling now 😁
